services:
  db:
    image: postgres:16
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: geoiam_test

  geoiam:
    image: geoiam:latest
    container_name: geoiam
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://test:test@db/geoiam_test
